In this file, the goal is to take a day's worth of data, and calculate the cumulative distance traveled by a single scooter. Since we are given a lat long, the plan is to group by a scooters ID, calculate cumulative distance, and then ungroup the data.

In [2]:
import pandas as pd
import geopandas as gpd

In [14]:
Scooters_2023_05_11 = pd.read_csv('Data/Scooters 2023-05-11.csv', index_col=0)
Scooters_2023_05_11.head()

,Unnamed: 0,title,id,networkName,networkId,color,textColor,latitude,longitude,type,subtitle,stationProperties,reverse_cycle,time
0,0,Link Scooter,decba7fc-debf-472a-8d51-2b7244d063e6,LINK,1319,E5FF01,07000E,34.06588,-118.44820,electric-scooter,NaN,NaN,-75,2023-05-17 09:00:19.484399
1,1,Link Scooter,808f4162-124f-48cc-a026-f17f61c2dcad,LINK,1319,E5FF01,07000E,34.06377,-118.44517,electric-scooter,NaN,NaN,-75,2023-05-17 09:00:19.484399
2,2,Link Scooter,688ad54a-72e5-43d2-ad6f-690fac0c02ae,LINK,1319,E5FF01,07000E,34.06960,-118.43841,electric-scooter,NaN,NaN,-75,2023-05-17 09:00:19.484399
3,3,Link Scooter,bb467505-a28f-4f80-ae8c-0b1fc3b6e584,LINK,1319,E5FF01,07000E,34.06377,-118.44513,electric-scooter,NaN,NaN,-75,2023-05-17 09:00:19.484399
4,4,Link Scooter,b7cc8424-a9d2-4fe7-ba70-859639d39584,LINK,1319,E5FF01,07000E,34.06563,-118.44002,electric-scooter,NaN,NaN,-75,2023-05-17 09:00:19.484399

In [16]:
grouped_scooters = Scooters_2023_05_11.groupby('id')[['latitude','longitude']].count()

In [17]:
print(grouped_scooters)

                                      latitude  longitude
id
00010341-50ee-4a00-89c1-24dc22d47a49        19         19
00010fc1-31ae-42cd-aad9-beee75607bf1        19         19
00070b4c-bcbe-4e41-b973-322fbacbef13        21         21
000786af-be23-4607-a979-cf8a94a850b1        10         10
0008d052-3d4f-4068-b421-ab5557a3e8c0        15         15
...                                        ...        ...
fffb3a72-cf8f-4ddb-954a-781dbd4caefe        20         20
fffbd959-b7c6-4405-9f7d-1b2b1fb20fcb        13         13
fffcd0ec-a401-48d0-8841-5eebe752707b        21         21
fffd64e7-4e7c-4c0a-8f36-922883f03e6d        20         20
ffff6289-a828-48ed-be7f-a37ac4c48eb7        22         22

[46749 rows x 2 columns]

In [18]:
Scooters_2023_05_11.groupby(['id']).count()

,Unnamed: 0,title,networkName,networkId,color,textColor,latitude,longitude,type,subtitle,stationProperties,reverse_cycle,time
id,,,,,,,,,,,,,
00010341-50ee-4a00-89c1-24dc22d47a49,19,19,19,19,19,19,19,19,19,0,0,19,19
00010fc1-31ae-42cd-aad9-beee75607bf1,19,19,19,19,19,19,19,19,19,0,0,19,19
00070b4c-bcbe-4e41-b973-322fbacbef13,21,21,21,21,21,21,21,21,21,0,0,21,21
000786af-be23-4607-a979-cf8a94a850b1,10,10,10,10,10,10,10,10,10,0,0,10,10
0008d052-3d4f-4068-b421-ab5557a3e8c0,15,15,15,15,15,15,15,15,15,0,0,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffb3a72-cf8f-4ddb-954a-781dbd4caefe,20,20,20,20,20,20,20,20,20,0,0,20,20
fffbd959-b7c6-4405-9f7d-1b2b1fb20fcb,13,13,13,13,13,13,13,13,13,0,0,13,13
fffcd0ec-a401-48d0-8841-5eebe752707b,21,21,21,21,21,21,21,21,21,0,0,21,21
fffd64e7-4e7c-4c0a-8f36-922883f03e6d,20,20,20,20,20,20,20,20,20,0,0,20,20
ffff6289-a828-48ed-be7f-a37ac4c48eb7,22,22,22,22,22,22,22,22,22,0,0,22,22