In this file, the goal is to take a day's worth of data, and calculate the cumulative distance traveled by a single scooter. Since we are given a lat long, the plan is to group by a scooters ID, calculate cumulative distance, and then ungroup the data.

In [1]:
import pandas as pd
import geopandas as gpd

In [10]:
Scooters_2023_05_11 = pd.read_csv('Data/Scooters 2023-05-17.csv', index_col=0)
Scooters_2023_05_11.head()

,title,id,networkName,networkId,color,textColor,latitude,longitude,type,subtitle,stationProperties,time
0,Link Scooter,8c088413-0b87-49a6-8ece-b91b408545c1,LINK,1319,E5FF01,07000E,34.06379,-118.44610,electric-scooter,NaN,NaN,2023-05-17 09:00:19.484399
1,Link Scooter,76f5520c-94b7-46df-af20-c41adf63dcf1,LINK,1319,E5FF01,07000E,34.06743,-118.44965,electric-scooter,NaN,NaN,2023-05-17 09:00:19.484399
2,Link Scooter,5e260c79-05bb-4aeb-80e1-fe1c5d5e8639,LINK,1319,E5FF01,07000E,34.06710,-118.45234,electric-scooter,NaN,NaN,2023-05-17 09:00:19.484399
3,Link Scooter,0262bef4-168c-4db8-ab0a-cf5b20214107,LINK,1319,E5FF01,07000E,34.06964,-118.45061,electric-scooter,NaN,NaN,2023-05-17 09:00:19.484399
4,Gateway Plaza,bcycle_lametro_4613,Metro Bike Share,554,383838,FFFFFF,34.06975,-118.44535,station,2 bikes - 1 e-bike - 9 docks,"{'counts': {'bike': 2, 'electric-bike': 1, 'do...",2023-05-17 09:00:19.484399

In [11]:
grouped_scooters = Scooters_2023_05_11.groupby('id').count()

In [12]:
print(grouped_scooters)

                                      title  networkName  networkId  color  \
id
00002159-5df2-423b-9c44-2fa47d48acef      1            1          1      1
0000a44c-0e12-43b7-b222-b698e92fb9fd      1            1          1      1
000296cb-662f-4469-8d75-4b29a13b3d56      1            1          1      1
000610b3-ea50-471d-8287-35517258bf4c      1            1          1      1
0009083d-3373-4bae-aafd-15b6000f6900      1            1          1      1
...                                     ...          ...        ...    ...
fff82fc0-b942-4024-a817-40d57e580ea9      1            1          1      1
fff8b0d9-c3d4-42ac-8f3f-1fd2db87689c      1            1          1      1
fff9d070-0dfa-4861-9896-09ef7ef70e6b      1            1          1      1
fffb576f-441c-4be6-b125-115f4b6690bd      1            1          1      1
ffff7fc0-19ca-4eb1-a87f-fbf43c495319      1            1          1      1

                                      textColor  latitude  longitude  type  \
id
00002159-5df2-423b-9c44-2fa47d48acef          1         1          1     1
0000a44c-0e12-43b7-b222-b698e92fb9fd          1         1          1     1
000296cb-662f-4469-8d75-4b29a13b3d56          1         1          1     1
000610b3-ea50-471d-8287-35517258bf4c          1         1          1     1
0009083d-3373-4bae-aafd-15b6000f6900          1         1          1     1
...                                         ...       ...        ...   ...
fff82fc0-b942-4024-a817-40d57e580ea9          1         1          1     1
fff8b0d9-c3d4-42ac-8f3f-1fd2db87689c          1         1          1     1
fff9d070-0dfa-4861-9896-09ef7ef70e6b          1         1          1     1
fffb576f-441c-4be6-b125-115f4b6690bd          1         1          1     1
ffff7fc0-19ca-4eb1-a87f-fbf43c495319          1         1          1     1

                                      subtitle  stationProperties  time
id
00002159-5df2-423b-9c44-2fa47d48acef         0                  0     1
0000a44c-0e12-43b7-b222-b698e92fb9fd         0                  0     1
000296cb-662f-4469-8d75-4b29a13b3d56         0                  0     1
000610b3-ea50-471d-8287-35517258bf4c         0                  0     1
0009083d-3373-4bae-aafd-15b6000f6900         0                  0     1
...                                        ...                ...   ...
fff82fc0-b942-4024-a817-40d57e580ea9         0                  0     1
fff8b0d9-c3d4-42ac-8f3f-1fd2db87689c         0                  0     1
fff9d070-0dfa-4861-9896-09ef7ef70e6b         0                  0     1
fffb576f-441c-4be6-b125-115f4b6690bd         0                  0     1
ffff7fc0-19ca-4eb1-a87f-fbf43c495319         0                  0     1

[43748 rows x 11 columns]

In [18]:
Scooters_2023_05_11.groupby(['id']).count()

,Unnamed: 0,title,networkName,networkId,color,textColor,latitude,longitude,type,subtitle,stationProperties,reverse_cycle,time
id,,,,,,,,,,,,,
00010341-50ee-4a00-89c1-24dc22d47a49,19,19,19,19,19,19,19,19,19,0,0,19,19
00010fc1-31ae-42cd-aad9-beee75607bf1,19,19,19,19,19,19,19,19,19,0,0,19,19
00070b4c-bcbe-4e41-b973-322fbacbef13,21,21,21,21,21,21,21,21,21,0,0,21,21
000786af-be23-4607-a979-cf8a94a850b1,10,10,10,10,10,10,10,10,10,0,0,10,10
0008d052-3d4f-4068-b421-ab5557a3e8c0,15,15,15,15,15,15,15,15,15,0,0,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffb3a72-cf8f-4ddb-954a-781dbd4caefe,20,20,20,20,20,20,20,20,20,0,0,20,20
fffbd959-b7c6-4405-9f7d-1b2b1fb20fcb,13,13,13,13,13,13,13,13,13,0,0,13,13
fffcd0ec-a401-48d0-8841-5eebe752707b,21,21,21,21,21,21,21,21,21,0,0,21,21
fffd64e7-4e7c-4c0a-8f36-922883f03e6d,20,20,20,20,20,20,20,20,20,0,0,20,20
ffff6289-a828-48ed-be7f-a37ac4c48eb7,22,22,22,22,22,22,22,22,22,0,0,22,22

In [22]:
Scooters_2023_05_11 = pd.read_csv('Data/Scooters 2023-05-11.csv', index_col=0)
Scooters_2023_05_18 = pd.read_csv('Data/Scooters 2023-05-18.csv')

In [24]:
Scooters_2023_05_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25663 entries, 0 to 25662
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         25663 non-null  int64
 1   title              25663 non-null  object
 2   id                 25663 non-null  object
 3   networkName        25663 non-null  object
 4   networkId          25663 non-null  int64
 5   color              25663 non-null  object
 6   textColor          25663 non-null  object
 7   latitude           25663 non-null  float64
 8   longitude          25663 non-null  float64
 9   type               25663 non-null  object
 10  subtitle           103 non-null    object
 11  stationProperties  103 non-null    object
 12  time               25663 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 2.5+ MB

In [25]:
Scooters_2023_05_11.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 731998 entries, 0 to 731997
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         731998 non-null  int64
 1   title              731998 non-null  object
 2   id                 731998 non-null  object
 3   networkName        731998 non-null  object
 4   networkId          731998 non-null  int64
 5   color              731998 non-null  object
 6   textColor          731998 non-null  object
 7   latitude           731998 non-null  float64
 8   longitude          731998 non-null  float64
 9   type               731998 non-null  object
 10  subtitle           3148 non-null    object
 11  stationProperties  3148 non-null    object
 12  reverse_cycle      731998 non-null  int64
 13  time               731998 non-null  object
dtypes: float64(2), int64(3), object(9)
memory usage: 83.8+ MB

In [ ]:
   "scooters_sorted = Scooters_2023_05_11.sort_values(by=['id', 'time'])\n"

 "scooters_sorted_gdf = gpd.GeoDataFrame(scooters_sorted,geometry=gpd.points_from_xy(scooters_sorted.longitude, scooters_sorted.latitude),\n",
    "                       crs=\"EPSG:4326\")\n",
    "#scooters_sorted_gdf.head()"



for i in range(1, len(scooters_sorted_gdf)):\n",
    "    if scooters_sorted_gdf.loc[i-1,'id'] == scooters_sorted_gdf.loc[i,'id']:\n",
    "        scooters_sorted_gdf.loc[i,'cumulative_distance'] = scooters_sorted_gdf.loc[i, 'geometry'].distance(scooters_sorted_gdf.loc[i+1, 'geometry'])\n",
    "    else:\n",
    "        \n",
    "        scooters_sorted_gdf.loc[i,'cumulative_distance'] = np.nan\n",
    "scooters_sorted_gdf.head(10)"